'use client';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@/hooks/useUserContext';
import { TrpcContext } from '@/hooks/TrpcContext';
import { CookiesProvider } from 'react-cookie';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <CookiesProvider>
        <TrpcContext>
          <UserProvider>
            <body className="bg-background text-foreground font-sans antialiased min-h-screen">
              {children}
            </body>
          </UserProvider>
        </TrpcContext>
      </CookiesProvider>
    </html>
  );
}
